added Podnos
CntoDev/artillery_solver pull request #6
Opened 2017-07-03 14:33 UTC by milivojm

Arg0n added 2B14-1 Podnos to list of weapons.

2017-07-03 16:47 UTC, lastmikoi approved these changes

2017-07-12 10:43 UTC, isakic requested changes
After consulting Argon it seems the default unit for Podnos is wrong: units[1] is NATO mrad, should be units[0] i.e. degrees. This should be fixed before merging.

2017-07-12 17:50 UTC, milivojm commented
Hopefully that's fixed now.

2017-07-12 19:02 UTC, isakic approved these changes

2017-07-12 20:48 UTC, merged